### ISSUE TITLE
0.0.3 does not appear on dub.pm

### ISSUE THREAD

**Issue by ichordev** [atilaneves/fearless#4]
The latest version of this package that appears on dub.pm is `~master` from 2019-Jan-03:
[https://code.dlang.org/packages/fearless/~master](https://code.dlang.org/packages/fearless/~master)

I think there should bes a way for you to manually tell dub.pm to check the repository. It'd be great to not have to use `dub add-local` to use the latest version of the package. :pray:

**Comment by atilaneves** [comment]
Huh, thanks. I just did a manual update and 0.0.3 is up there now.
